-- VIVI · ViviendAI
-- Ejecutar en Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.vivi_leads (
    id uuid primary key default gen_random_uuid(),
    lead_code text not null unique,
    full_name text not null,
    normalized_name text not null,
    id_type text not null,
    id_number text,
    income_range text not null,
    income_monthly bigint default 0,
    affiliated boolean not null default false,
    affiliation_type text,
    negative_report boolean not null default false,
    source text not null,
    campaign text not null,
    campaign_id text,
    adset_id text,
    ad_id text,
    form_id text,
    meta_lead_id text,
    utm_source text,
    utm_medium text,
    utm_campaign text,
    utm_content text,
    purchase_horizon text,
    savings_range text,
    preferred_project text,
    bedrooms integer,
    telegram_username text,
    score integer not null default 0 check (score between 0 and 100),
    rating text not null,
    duplicate_of text,
    commercial_summary text,
    colsubsidio_subsidy bigint default 0,
    concurrent_potential bigint default 0,
    max_monthly_payment bigint default 0,
    conversation_profile_json jsonb,
    propensity_score integer default 0 check (propensity_score between 0 and 100),
    propensity_priority text,
    profile_diagnosis text,
    profile_completed_at timestamptz,
    funnel_status text not null default 'NUEVO',
    crm_status text not null default 'PROFILE_PENDING',
    crm_payload jsonb,
    consent boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.vivi_integration_events (
    id bigint generated by default as identity primary key,
    lead_code text references public.vivi_leads(lead_code) on delete cascade,
    event_type text not null,
    status text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists vivi_leads_document_idx
    on public.vivi_leads(id_number);
create index if not exists vivi_leads_campaign_idx
    on public.vivi_leads(campaign_id);
create index if not exists vivi_leads_crm_status_idx
    on public.vivi_leads(crm_status);
create index if not exists vivi_leads_funnel_status_idx
    on public.vivi_leads(funnel_status);
create index if not exists vivi_events_lead_created_idx
    on public.vivi_integration_events(lead_code, created_at desc);

alter table public.vivi_leads enable row level security;
alter table public.vivi_integration_events enable row level security;

revoke all on table public.vivi_leads from anon, authenticated;
revoke all on table public.vivi_integration_events from anon, authenticated;
grant select, insert, update, delete on table public.vivi_leads to service_role;
grant select, insert, update, delete on table public.vivi_integration_events to service_role;
grant usage, select on sequence public.vivi_integration_events_id_seq to service_role;

create or replace function public.vivi_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists vivi_leads_set_updated_at on public.vivi_leads;
create trigger vivi_leads_set_updated_at
before update on public.vivi_leads
for each row execute function public.vivi_set_updated_at();

comment on table public.vivi_leads is
    'Leads perfilados de VIVI. Acceso exclusivo del backend con secret/service role.';
comment on table public.vivi_integration_events is
    'Trazabilidad técnica sin exposición pública.';
